<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form subscribe"
    novalidate
    action="<?php echo $block->getFormActionUrl() ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail-1">
    <div class="field newsletter">
        <label class="label" for="newsletter"><span><?php echo __('Sign Up for Our Newsletter:') ?></span></label>
        <div class="control">
            <input name="email" placeholder="<?php echo __('Email Address'); ?>" type="email" id="newsletter"
                        data-validate="{required:true, 'validate-email':true}"/>
              <div class="g-recaptcha" data-sitekey="6LfOLH4UAAAAADMuOtV45NAKBIakthCd-_6UpCKl" data-callback="callback"></div>            
            <button class="action subscribe primary" title="<?php echo __('Subscribe') ?>" type="submit">
                <span><?php echo __('Go!') ?></span>
            </button>
        </div>
    </div>
</form>
<script src='https://www.google.com/recaptcha/api.js' async defer></script>
<script type="text/javascript">
$("#newsletter-validate-detail-1").submit(function(event) {
   var recaptcha = $("#g-recaptcha-response").val();
   if (recaptcha === "") {
      event.preventDefault();
      alert("Please check the recaptcha");
   }
});
</script>