<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\View\Options */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();
$params = $block->getRequest()->getParams(); 
$edit='';
if(sizeof($params)>1){    
  $edit='yes';
}else{
    $edit = 'no';
}
?>
<input type="hidden" id="edit_product" name="edit_product" value="<?php echo $edit;?>">

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php $_productId = $block->getProduct()->getId() ?>
<?php $_productPrice = $block->getProduct()->getPrice();?>

<div class = "base_url" style="display: none"><?php echo $block->getBaseUrl()?></div>
<input id = "base_price" type = "hidden" name="base_price" value = "<?php echo $_productPrice;?>">
<?php if (count($_options)):?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceOptions": {
                "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>,
                "controlContainer": ".field",
                "priceHolderSelector": "[data-product-id='<?php echo $block->escapeHtml($_productId)?>'][data-role=priceBox]"
            }
        }
    }
</script>
    <?php foreach ($_options as $_option): ?>
        <?php echo $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>

