<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
 $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
 $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
 $currencySymbol = $currency->getCurrencySymbol();

$customClass = '';
$customDivclass = '';

if($_option->getTitle() == 'Number Of Pages'){    
    $customClass = "number-of-pages";    
}

if($_option->getTitle() == "Preferred Installation Date"){
  $customDivclass = "preferred-date";
}

?>
<div class="custom-option number-custom-option <?php echo $customDivclass; ?>" <?php echo ($_option->getTitle() == "Preferred Installation Date") ? 'style="display: none"' : '' ?>>
  <div class="field<?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_AREA) {
      echo ' textarea';
  } ?><?php /* @escapeNotVerified */ echo $class ?>" <?php echo ($_option->getTitle() == "Custom Size") ? 'style="display: none"' : '' ?> >
      <label class="label" for="options_<?php /* @escapeNotVerified */ echo $_option->getId() ?>_text">
          <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
          <?php /* @escapeNotVerified */ echo $block->getFormatedPrice() ?>
      </label>

      <div class="control">
          <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_FIELD): ?>
              <?php $_textValidate = null;
              if ($_option->getIsRequire()) {
                  $_textValidate['required'] = true;
              }
              if ($_option->getMaxCharacters()) {
                  $_textValidate['maxlength'] = $_option->getMaxCharacters();
              }
              ?>
              <input type="text"
                     id="options_<?php /* @escapeNotVerified */ echo $_option->getId() ?>_text"
                     class="input-text product-custom-option <?php echo $customClass; ?> <?php echo ($_option->getTitle() == "Custom Size") ? 'custom-size-option' : ''?> <?php echo ($_option->getTitle() == "Preferred Installation Date") ? 'preferred-date-datepicker' : ''?>" 
                     <?php if (!empty($_textValidate)) {?>
                     data-validate="<?php echo  $block->escapeHtml(json_encode($_textValidate));?>"
                     <?php } ?>
                     name="options[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                     data-selector="options[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                     value="<?php echo $block->escapeHtml($block->getDefaultValue()) ?>"/>
          <?php elseif ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_AREA): ?>
              <?php $_textAreaValidate = null;
              if ($_option->getIsRequire()) {
                  $_textAreaValidate['required'] = true;
              }
              if ($_option->getMaxCharacters()) {
                  $_textAreaValidate['maxlength'] = $_option->getMaxCharacters();
              }
              ?>
              <textarea id="options_<?php /* @escapeNotVerified */ echo $_option->getId() ?>_text"
                        class="product-custom-option"
                      <?php if (!empty($_textAreaValidate)) {?>
                          data-validate="<?php echo $block->escapeHtml(json_encode($_textAreaValidate));?>"
                      <?php } ?>
                        name="options[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        data-selector="options[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        rows="5"
                        cols="25"><?php echo $block->escapeHtml($block->getDefaultValue()) ?></textarea>
          <?php endif; ?>
          <?php if ($_option->getMaxCharacters()): ?>
              <p class="note"><?php /* @escapeNotVerified */ echo __('Maximum number of characters:') ?>
                  <strong><?php /* @escapeNotVerified */ echo $_option->getMaxCharacters() ?></strong></p>
          <?php endif; ?>
      </div>
  </div>
</div>
<?php
if($_option->getTitle() == 'Preferred Installation Date'){
  ?>
<div id="preferred-date-text" class="preferred-date-text" style="display:none">
  <p>We wiil contact to confirm availability</p>
</div>
 <div class="price-box production-time-price-final-price" data-role="priceBox"> 
  <span class="price-container-show price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">   
      <label class="final-price-label">Printing Cost </label>
      <div class="final-price-value">
        <span class="currency-symbol"><?php echo $currencySymbol?> </span>
        <span class="show_price"></span>     
      </div>  
  </span>
</div>
<div class="price-box production-time-price-final-price installation-price" data-role="priceBox"> 
  <span class="price-container-show price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">   
      <label class="final-price-label">Installation Cost </label>
      <div class="final-price-value">
        <span class="currency-symbol"><?php echo $currencySymbol?> </span>
        <span class="show_installation_price"></span>     
      </div>  
  </span>
  <div id="installation-text" style="text-align: left;">
    <p>Within 5 miles of San Francisco</p>
    <p>Additional travel cost will apply for other cities</p>
  </div>
</div>
<div class="price-box production-time-price-final-price" data-role="priceBox"> 
  <span class="price-container-show price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">   
      <label class="final-price-label">Total Cost </label>
      <div class="final-price-value">
        <span class="currency-symbol"><?php echo $currencySymbol?> </span>
        <span class="show_total_price"></span>     
      </div>  
  </span>
</div>
<div id = "payment-error"  style="color:red;display: none";>
  <p>This product has a required minimum order of $25.</p>
</div>
<div id = "width-error"  style="color:red;display: none";>
  <p>Please Select Width!!</p>
</div>
<div id = "height-error"  style="color:red;display: none";>
  <p>Please Select Height!!</p>
</div>
<?php }
?>
<script type="text/javascript">
    require(['jquery','jquery/ui','uiwidget'
        ], function ($) { 
          $(".preferred-date-datepicker").datepicker({
            minDate: 0,
          });
    });
</script>