<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\AddressAutocomplete\Block\Checkout */
?>
<script>
    require.config({
        map: {
            '*': {
                'magePalGoogleMapPlaceLibrary': 'https://maps.googleapis.com/maps/api/js?key=AIzaSyB6NVryKG9b4ORs4wbTGDGVvouGihlRnPU&libraries=places&v=weekly'
            }
        }
    });
</script>
