<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_option = $block->getOption(); ?>
<?php $_fileInfo = $block->getFileInfo(); ?>
<?php $_fileExists = $_fileInfo->hasData(); ?>
<?php $_fileName = 'options_' . $_option->getId() . '_file'; ?>
<?php $_fieldNameAction = $_fileName . '_action'; ?>
<?php $_fieldValueAction = $_fileExists ? 'save_old' : 'save_new'; ?>
<?php $_fileNamed = $_fileName . '_name'; ?>
<?php $class = ($_option->getIsRequire()) ? ' required' : '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();
$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
$mediaPath  =   $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();  
$filePath;
 ?>
<div class = "file-uploaded">
    <label>File upload (PDF files are preferred)</label>
    <div class="field <?php /* @escapeNotVerified */ echo $class; ?>">
        <?php if ($_fileExists):
        $pieces = explode('.', $_fileInfo->getTitle());
          $extensions = array_pop($pieces);
          ?>
        <div class="control">
          <?php if($extensions == 'pdf'){
                  $filePath =  $base_url.'pub/media/custom_options/pdf.png';
                }
                else if($extensions == 'ppt'){
                  $filePath =  $base_url.'pub/media/custom_options/ppt.png';
                }else if($extensions == 'doc' || $extensions == 'docx'){
                  $filePath =  $base_url.'pub/media/custom_options/doc.png';
                }else if($extensions == 'psd'){
                  $filePath =  $base_url.'pub/media/custom_options/psd.png';
                }else if($extensions == 'tiff'){
                  $filePath =  $base_url.'pub/media/custom_options/tiff.png';
                }else if($extensions == 'ai'){
                  $filePath =  $base_url.'pub/media/custom_options/ai.png';
                }else if($extensions == 'eps'){

                  $filePath =  $base_url.'pub/media/custom_options/eps.jpg';
                  
                }
                else if($extensions == 'jpg' || $extensions == 'png' ||$extensions == 'jpeg'){
                  $filePath =  $base_url.'pub/media/'.$_fileInfo->getData('quote_path');
                  
                }
                //echo $filePath;
                ?>
             <div id="preview-update">
              <img src="<?php if(isset($filePath)) echo $filePath;?>">
                <span id="file-name" class="<?php /* @noEscape */ echo $_fileNamed ?>"><?php echo $block->escapeHtml($_fileInfo->getTitle()); ?></span>
                
                 <a href="javascript:void(0)" class="label change_file" id="change-<?php /* @noEscape */ echo $_fileName ?>" >
                <?php /* @escapeNotVerified */ echo __('Change') ?>
                </a>
            </div> 
            
           <!--  <?php if (!$_option->getIsRequire()): ?>
                <input type="checkbox" id="delete-<?php /* @escapeNotVerified */ echo $_fileName ?>" />
                <span class="label"><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
            <?php endif; ?> -->
        </div>
        <?php endif; ?>
        <div class="control " id="input-box-<?php /* @escapeNotVerified */ echo $_fileName ?>"
                 data-mage-init='{"priceOptionFile":{
                    "fileName":"<?php /* @noEscape */ echo $_fileName ?>",
                    "fileNamed":"<?php /* @noEscape */ echo $_fileNamed ?>",
                    "fieldNameAction":"<?php /* @escapeNotVerified */ echo $_fieldNameAction ?>",
                    "changeFileSelector":"#change-<?php /* @escapeNotVerified */ echo $_fileName ?>",
                    "deleteFileSelector":"#delete-<?php /* @escapeNotVerified */ echo $_fileName ?>"}
                 }'
                <?php echo $_fileExists ? 'style="display:none"' : '' ?>>
            <div class = "image-editor"> 
            <img id="image_upload_preview1" src="#" alt="your image" style="display: none; width:auto;height:200px"/> 
            <div id="delete" style="display: none;">
               <button id="image_upload_preview_delete_button_other" title="Delete" type="button"/>
            </div>  
                <div class="upload-image">
                    <label class="label" for="<?php /* @noEscape */ echo $_fileName; ?>" id="<?php /* @noEscape */ echo $_fileName; ?>-label">
                        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span>
                        <?php /* @escapeNotVerified */ echo $block->getFormatedPrice() ?>
                    </label>
                    <input type="file"
                           name="<?php /* @escapeNotVerified */ echo $_fileName; ?>"
                           id="<?php /* @escapeNotVerified */ echo $_fileName; ?>"
                           class="product-custom-option<?php echo $_option->getIsRequire() ? ' required' : '' ?> cropit-image-input"
                           <?php echo $_fileExists ? 'disabled="disabled"' : '' ?> />
                    
                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo $_fieldNameAction; ?>" value="<?php /* @escapeNotVerified */ echo $_fieldValueAction; ?>" />
                </div>  
               <div class="not-image" style="display: none;">
                    <div class="cropit-preview">                    
                    </div>
                     <div class="action">    
                        <!-- <input type="range" class="cropit-image-zoom-input"/>  -->  

                       <!--  <img src="#" class="cropit-image-zoom-input" id="decrement" min="0" max="1" step="0.01"  value="" >
                        <img src="#" class="cropit-image-zoom-input" id="increment" min="0" max="1" step="0.01"  value=""> -->
                       <!--  <button id="image_upload_preview_delete" title="Delete" type="button"/> -->
                        <button id="image_upload_preview_delete_button" title="Delete" type="button"/>
                        <button id="image_upload_preview_plus" title="Zoom In" type="button"/>
                        <button id="image_upload_preview_minus" title="Zoom out" type="button"/>
                    </div>    
              </div>
            </div> 
        </div>
    </div>
        
    
    <div class = "note-file"> 
      <label id="file-name"></label>
        <?php if ($_option->getFileExtension()): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('Compatible file extensions to upload')?>: <?php /* @escapeNotVerified */ echo $_option->getFileExtension() ?>
                </p>
            <?php endif; ?>
            <?php if ($_option->getImageSizeX() > 0): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('Maximum image width')?>: <strong><?php /* @escapeNotVerified */ echo $_option->getImageSizeX() ?> <?php /* @escapeNotVerified */ echo __('px.')?></strong>
                </p>
            <?php endif; ?>
            <?php if ($_option->getImageSizeY() > 0): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('Maximum image height')?>: <strong><?php /* @escapeNotVerified */ echo $_option->getImageSizeY() ?> <?php /* @escapeNotVerified */ echo __('px.')?></strong>
                </p>
            <?php endif; ?>
    </div>  
</div>    
<div class = "file-upload-error" style="color:red;display: none;"></div>      
<script>
     require([
          "jquery","cropit","Magento_Ui/js/form/components/group"
     ], function($){
            function readURL(input) {
             
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var filename = input.files[0].name;
             
                        $('#file-name').html(filename);
                        var data = filename.split('.').pop(); 

                        var value = data.toLowerCase();
                        console.log(value);
                        if(value == 'doc' || value == 'docx'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/doc.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);
                        }
                        else if(value == 'pdf'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/pdf.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'ppt'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/ppt.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'ai'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/ai.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }
                        else if(value == 'tiff'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/tiff.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'psd'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/psd.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'eps'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/eps.jpg';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'jpg' || value == 'png' ||value == 'jpeg'){
                            $('.file-upload-error').hide();
                            $('.upload-image').hide();
                            $('.not-image').show();
                            $('#image_upload_preview1').hide();
                            $('#delete').hide();
                            //$('#image_upload_preview').attr('src', e.target.result);    
                        }else{
                             $('.file-upload-error').html('This File Format is Not Supported.');
                             $('.file-upload-error').show();
                             $('#file-name').html('');
                             $('.cropit-image-input').val('');
                             $('.upload-image').show();
                             $('.not-image').hide();
                             $('#image_upload_preview1').hide();
                             $('#delete').hide();            
                        }
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            } 
        $(".cropit-image-input").change(function() {
            $('.not-image').hide();
            readURL(this);
        });
        // jQuery('.image-editor').cropit('zoom', .3);
        

        var i = 0 ;
        $('#image_upload_preview_plus').click(function(){
            i +=0.2;
            i = parseFloat(Number(i).toFixed(2));
            if (i < 1.1) {
                //jQuery('.image-editor').cropit('offset', { x: 0, y: 0 });
                console.log("i+"+i);
                jQuery('.image-editor').cropit('zoom', i);
            }else{
                i = 1 ;
            }
        });
        $('#image_upload_preview_minus').click(function(){
            i -=0.2;
           i = parseFloat(Number(i).toFixed(2));
            if(i > 0){
                //jQuery('.image-editor').cropit('offset', { x: 0, y: 0 });
                console.log("i-"+i);
                jQuery('.image-editor').cropit('zoom', i);
            }else{
                i = 0 ;
            }
        });
        $('.image-editor').cropit({
            onImageLoaded: function(){
                //console.log(event);
                //alert('sdfg');
                jQuery('.image-editor').cropit('offset', { x: 0, y: 0 });
            },
        });
          var counter = 0;
        $('.change_file').click(function(){
            $('#preview-update').hide();
         });
        $("#image_upload_preview_delete_button").click(function() {
             //var id = '<?php /* @escapeNotVerified */ echo $_fileName; ?>';
             //console.log(id);
             $('#file-name').html('');
             $('.cropit-image-input').val('');
             $('.upload-image').show();
             $('.not-image').hide();
             $('#image_upload_preview1').hide();
             $('#delete').hide();            
        });   
        $("#image_upload_preview_delete_button_other").click(function() {
             //var id = '<?php /* @escapeNotVerified */ echo $_fileName; ?>';
             //console.log(id);
             $('#file-name').html('');
             $('.cropit-image-input').val('');
             $('.upload-image').show();
             $('.not-image').hide();
             $('#image_upload_preview1').hide();
             $('#delete').hide();            
        });       
       });
</script>

     <style>
      .cropit-preview {
        background-color: #f8f8f8;
        background-size: cover;
        border: 1px solid #ccc;
        border-radius: 3px;
        width: 300px;
        height:200px;
      }

      .cropit-preview-image-container {
        cursor: move;
      }
      /*.cropit-preview-image { 
        margin: auto;
        position: absolute;
        top: 50%;
        left: -10%;
        bottom: -50%;
        right: -30%;
        max-width: inherit !important; }*/

      /*.image-size-label {
        margin-top: 10px;
      }*/

      .cropit-preview-image {
         transform-origin: center center !important;
        display: table-cell;
        vertical-align: middle;
        /*transform: translate(-0px, -0px) !important;*/   
      }

      input, .export {
        display: block;
      }

      button {
        margin-top: 10px;
      }
    </style>
