<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$params = $block->getRequest()->getParams(); 
?>
<?php $_option = $block->getOption(); ?>
<?php $_fileInfo = $block->getFileInfo(); ?>
<?php $_fileExists = $_fileInfo->hasData();
 ?>
<?php $_fileName = 'options_' . $_option->getId() . '_file'; 
?>
<?php $_fieldNameAction = $_fileName . '_action'; ?>
<?php $_fieldValueAction = $_fileExists ? 'save_old' : 'save_new'; ?>
<?php $_fileNamed = $_fileName . '_name'; ?>
<?php $class = ($_option->getIsRequire()) ? ' required' : '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();
$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
$mediaPath  =   $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath(); 
$checkoutSession = $objectManager->create('Magento\Checkout\Model\Session');
$quote_item = $objectManager->create('\Mangoit\MultiplyOptions\Helper\QuantityCalculate');      
$filePath;
 ?>
<div class = "file-uploaded">
    <label class="file-upload-text"><?php echo __('File Upload - 200 MB max size (PDFs preferred)')?></label>
    <div class="field <?php /* @escapeNotVerified */ echo $class; ?>">
        <?php if ($_fileExists):
        $pieces = explode('.', $_fileInfo->getTitle());
          $extensions = strtolower(array_pop($pieces));

          ?>
        <div class="control">
          <?php if($extensions == 'pdf' || $extensions == 'psd' || $extensions == 'tiff' || $extensions == 'ai'|| $extensions == 'eps' || $extensions == 'jpg' || $extensions == 'png' ||$extensions == 'jpeg'){
                    $quote_path = $quote_item->getImgData($params['id']);                    
                    $filePath =  $base_url.'pub/media/'.$quote_path;                  
                }
                else if($extensions == 'ppt' || $extensions == 'pptx'){
                  $filePath =  $base_url.'pub/media/custom_options/ppt.png';

                }else if($extensions == 'doc' || $extensions == 'docx'){
                  $filePath =  $base_url.'pub/media/custom_options/doc.png';
                }
                ?>
             <div id="preview-update">              
              <div class="preview-image">
                <img src="<?php if(isset($filePath)) echo $filePath;?>" style="width:200px;">
              </div>  
              <div class="preview-content">
                    <span id="file-name" class="<?php /* @noEscape */ echo $_fileNamed ?>"><?php echo $block->escapeHtml($_fileInfo->getTitle()); ?></span>
                      <span>
                          <a href="javascript:void(0)" class="label change_file" id="change-<?php /* @noEscape */ echo $_fileName ?>" >
                        <?php /* @escapeNotVerified */ echo __('Change') ?>
                        </a>
                      </span>
              </div>    
            </div>
                
             
            
             <?php if (!$_option->getIsRequire()): ?>
                  <div class="delete-checked" style="display: none;">
                    <input class="delete-file" type="checkbox" id="delete-<?php /* @escapeNotVerified */ echo $_fileName ?>" />
                    <span class="label"><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                  </div>  
               
            <?php endif; ?> 
        </div>
        <?php endif; ?>
        <div class="control " id="input-box-<?php /* @escapeNotVerified */ echo $_fileName ?>"
                 data-mage-init='{"priceOptionFile":{
                    "fileName":"<?php /* @noEscape */ echo $_fileName ?>",
                    "fileNamed":"<?php /* @noEscape */ echo $_fileNamed ?>",
                    "fieldNameAction":"<?php /* @escapeNotVerified */ echo $_fieldNameAction ?>",
                    "changeFileSelector":"#change-<?php /* @escapeNotVerified */ echo $_fileName ?>",
                    "deleteFileSelector":"#delete-<?php /* @escapeNotVerified */ echo $_fileName ?>"}
                 }'
                <?php echo $_fileExists ? 'style="display:none"' : '' ?>>
            <div class = "image-editor"> 
              
            <img id="image_upload_preview1" src="#" alt="your image" style="display: none; width:auto;height:200px"/> 
            <div id="delete" style="display: none;">
               <button id="image_upload_preview_delete_button_other" title="Delete" type="button"/>
            </div>  
                <div class="upload-image">
                  <div class="image-uploader" style="display: none;">
                    <img src="<?php echo $block->getBaseUrl().'pub/media/custom_options/custom-loader-cropit.gif';?>">
                  </div>
                    <!-- The global progress bar -->
                      <div id="progress" class="progress" style="display: none;">
                          <div class="progress-bar progress-bar-success"></div>
                      </div>
                    <!-- The container for the uploaded files -->
                    <div id="files" class="files"></div>
                    <label class="label labeluploadbtn"  for="<?php /* @noEscape */ echo $_fileName; ?>" id="<?php /* @noEscape */ echo $_fileName; ?>-label">
                        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span>
                        <?php /* @escapeNotVerified */ echo $block->getFormatedPrice() ?>
                    </label>
                    <input type="file"
                           name="<?php /* @escapeNotVerified */ echo $_fileName; ?>"
                           id="<?php /* @escapeNotVerified */ echo $_fileName; ?>"
                           class="product-custom-option<?php echo $_option->getIsRequire() ? ' required' : '' ?> cropit-image-input"
                           <?php echo $_fileExists ? 'disabled="disabled"' : '' ?> />
                    
                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo $_fieldNameAction; ?>" value="<?php /* @escapeNotVerified */ echo $_fieldValueAction; ?>" />
                </div>  
               <div class="not-image" style="display: none;">
                    <div class="cropit-preview"> 
                    <img class="cropit-preview-image" alt=""  src="">                   
                    </div>
                     <div class="action">    
                       
                        <button id="image_upload_preview_delete_button" title="Delete" type="button"/>
                        <button id="image_upload_preview_plus" title="Zoom In" type="button"/>
                        <!-- <button id="image_upload_preview_minus" title="Zoom out" type="button"/> -->
                    </div>    
              </div>
            </div> 
        </div>
    </div>
    <div class = "note-file"> 
      <label id="file-name"></label>
        <?php if ($_option->getFileExtension()): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('PDF files are preferred! Other file formats acceptable
include jpeg, jpg, png, tiff, eps, ai, psd, doc and ppt.')?> <?php /* @escapeNotVerified */ //echo $_option->getFileExtension() ?>
                </p>
            <?php endif; ?>
            <?php if ($_option->getImageSizeX() > 0): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('Maximum image width')?>: <strong><?php /* @escapeNotVerified */ echo $_option->getImageSizeX() ?> <?php /* @escapeNotVerified */ echo __('px.')?></strong>
                </p>
            <?php endif; ?>
            <?php if ($_option->getImageSizeY() > 0): ?>
                <p class="note">
                    <?php /* @escapeNotVerified */ echo __('Maximum image height')?>: <strong><?php /* @escapeNotVerified */ echo $_option->getImageSizeY() ?> <?php /* @escapeNotVerified */ echo __('px.')?></strong>
                </p>
            <?php endif; ?>
    </div>  
</div>    
<div class = "file-upload-error" style="color:red;display: none;"></div>    
<div id="custom-model-popup" style="text-align:center;display: none;">
    <img class="preview-image" alt=""  src="" />   
</div>

<script>
     require([
          "jquery","uiwidget",
        "frameTransport",
        "fileUpload","Magento_Ui/js/form/components/group"
     ], function($){
       var base_url = '<?php echo $block->getBaseUrl();?>'; 
       var file = '';

       $('.cropit-image-input').fileupload({
            url: base_url+'fileupload/',
            dataType: 'json',
            maxFileSize: 200000000, // Maximum File Size in Bytes - 200 MB
              acceptFileTypes: /(\.|\/)(?!pdf|png|jpeg|tiff|ai|ppt|pptx|psd|eps|doc|docx)$/i,  // Allowed File Types
           /* start:function(e,data){
              $('.labeluploadbtn').hide();
            },
            stop:function(e,data){
              $('.labeluploadbtn').show();
            },
            processfail: function (e, data) {
              alert('herere');
              console.log('Processing ' + data.files[data.index].name + ' failed.');
            },*/
            done: function (e, data) {
              var extensions = data.result.type;
              var file = base_url+'pub/media/'+data.result.path;

              //alert(extensions +'  ' +file);
              if(extensions == 'docx' || extensions == 'doc' || extensions == 'ppt' || extensions == 'pptx'){
                readURL(this);                    
              }else if(extensions =='pdf' ||extensions =='psd' ||extensions =='eps' ||extensions =='tiff'||extensions =='ai'||  extensions == 'jpg' || extensions == 'png' ||extensions == 'jpeg') {
                
                $('img.cropit-preview-image').attr('src',file);  
                $('img.preview-image').attr('src',file);  
                $('.labeluploadbtn').show();  
                $('.file-upload-error').hide();
                $('.upload-image').hide();
                $('.not-image').show();
                $('#image_upload_preview1').hide();
                $('#delete').hide();
                readURL(this);    
              }else{
                //$('.labeluploadbtn').hide(); 
                readURL(this);    
                /*$('.labeluploadbtn').hide();  
                if(data._response.result.path == 'Error')
                  {$('.image-uploader').show();
                   alert("This File Format is Not Supported."); 
                 }*/
              }     
            },
            progressall: function (e, data) {  
              $('#progress').show();
              var progress = parseInt(data.loaded / data.total * 100, 10);
              $('#progress .progress-bar').css(
                  'width',
                  progress + '%'
              );
              if(progress==100) {
                $('#progress').hide();
                $('.image-uploader').show();
              }
              
            }
        });
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var filename = input.files[0].name;    
                        $('#file-name').html(filename);
                        var data = filename.split('.').pop(); 
                        var value = data.toLowerCase();
                        if(value == 'doc' || value == 'docx'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/doc.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);
                        }
                      else if(value == 'ppt' || value=='pptx'){
                              src = '<?php echo $base_url ?>'+'pub/media/custom_options/ppt.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);

                        }else if(value == 'ai'){
                             /* src = '<?php echo $base_url ?>'+'pub/media/custom_options/ai.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);*/

                        }
                        else if(value == 'tiff'){
                             /* src = '<?php echo $base_url ?>'+'pub/media/custom_options/tiff.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);*/

                        }else if(value == 'psd'){
                             /* src = '<?php echo $base_url ?>'+'pub/media/custom_options/psd.png';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);*/

                        }else if(value == 'eps'){
                             /* src = '<?php echo $base_url ?>'+'pub/media/custom_options/eps.jpg';
                              $('.file-upload-error').hide();
                              $('.upload-image').hide();
                              $('#image_upload_preview1').show();
                              $('#delete').show();
                              $('.not-image').hide();
                              $('#image_upload_preview1').attr('src', src);*/

                        }else if(value == 'pdf' || value == 'jpg' || value == 'png' ||value == 'jpeg'){
/*
                            $('.file-upload-error').hide();
                            $('.upload-image').hide();
                            $('.not-image').show();
                            $('#image_upload_preview1').hide();
                            $('#delete').hide();*/
                            //$('#image_upload_preview').attr('src', e.target.result);    
                        } else {
                             $('.file-upload-error').html('This File Format is Not Supported.');
                             $('.file-upload-error').show();
                             $('#file-name').html('');
                             $('.cropit-image-input').val('');
                             $('.upload-image').show();
                             $('.not-image').hide();
                             $('#image_upload_preview1').hide();
                             $('#delete').hide();            
                        }
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            } 
        
      

        var i = 0 ;
        
        $('#image_upload_preview_minus').click(function(){
            i -=0.2;
           i = parseFloat(Number(i).toFixed(2));
            if(i > 0){
                //jQuery('.image-editor').cropit('offset', { x: 0, y: 0 });
               // jQuery('.image-editor').cropit('zoom', i);
            }else{
                i = 0 ;
            }
        });
         var base_url = '<?php echo $block->getBaseUrl();?>'; 
       
        
          var counter = 0;
        $('.change_file').click(function(){
            $('#preview-update').hide();
            $('.upload-image').show();
            $('.image-uploader').hide();
         });
        $("#image_upload_preview_delete_button").click(function() {
             //var id = '<?php /* @escapeNotVerified */ echo $_fileName; ?>';
             //console.log(id);
             $('#file-name').html('');
             $('.cropit-image-input').val('');
             $('.upload-image').show();
             $('.not-image').hide();
             $('.image-uploader').hide();
             $('#image_upload_preview1').hide();
             $('#delete').hide();            
        });   
        $("#image_upload_preview_delete_button_other").click(function() {
             //var id = '<?php /* @escapeNotVerified */ echo $_fileName; ?>';
             //console.log(id);
             $('#file-name').html('');
             $('.cropit-image-input').val('');
             $('.upload-image').show();
             $('.not-image').hide();
             $('.image-uploader').hide();
             $('#image_upload_preview1').hide();
             $('#delete').hide();            
        });       
       });
</script>
<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ], function($, modal){
       $('#image_upload_preview_plus').click(function(){
        var options = {
            type: 'popup',
            responsive: true,            
            title: "File Upload Preview", //write your popup title 
            buttons: [{
                text: $.mage.__('Submit'),
                class: 'button',
                click: function () {
                    console.log('Do something here......');
                    // Do something here........
                }
            }]
        };
        $('#custom-model-popup').show();
        var popupdata = $('<div />').append($('#custom-model-popup'));
        modal(options, popupdata);
        popupdata.modal('openModal');
      });  
    });
</script>
<style>
     .cropit-preview {
       background-color: #f8f8f8;
       background-size: cover;
       border: 1px solid #ccc;
       border-radius: 3px;
       /*width: 400px; */
       /*height:400px;*/
     }

     .modal-popup .modal-footer{
      display: none;
     }
      #preview-update div.preview-image {
        text-align: center;
      } 
      #preview-update div.preview-content span {
         position: static; top: 0px; padding-left: 15px; vertical-align: middle; margin-top: 15px;}

         #preview-update div.preview-content span a { 
          position: relative;
          display: inline-block;
          top: 16px;
          float: right;
        }
      

     .cropit-preview-image-container {
       cursor: move;
       text-align: center;
     }

     body #file-name {
       top: 39px;
       width: 73%;
       white-space: nowrap;
       text-overflow: ellipsis;
       overflow: hidden;
       display: inline-block;
     }
     /*.cropit-preview-image {
       margin: auto;
       position: absolute;
       top: 50%;
       left: -10%;
       bottom: -50%;
       right: -30%;
       max-width: inherit !important; }*/

     /*.image-size-label {
       margin-top: 10px;
     }*/
    .modal-popup .modal-inner-wrap{width:40% !important}
     .cropit-preview-image {
     /*   transform-origin: center center !important;*/
       display:inline-block;
       vertical-align: middle;
       /*transform: translate(-0px, -0px) !important;*/  
     }

     .cropit-preview-image { width: 100%;    }

     input, .export {
       display: block;
     }

     button {
       margin-top: 10px;
     }
     .file-upload-text {
        font-size: 13px !important;
      }
   </style>
