<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */


$_item = $block->getItem();
$product = $_item->getProduct();
$itemId = $_item->getItemId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of Object manager  
$checkoutSession = $objectManager->create('Magento\Checkout\Model\Session');
$quote_item = $objectManager->create('\Mangoit\MultiplyOptions\Helper\QuantityCalculate');
      
//die;
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$_options = $block->getOptionList();
$image_url = '';
foreach ($_options as $_option) {

     $_formatedOptionValue = $this->getFormatedOptionValue($_option);
     if($_option['option_type'] == 'file'){        
        $option = $objectManager->create('Magento\Quote\Model\Quote\Item\Option')->getCollection()
        ->addFieldToFilter('code', array('eq' => 'option_'.$_option['option_id']))
        ->addFieldToFilter('item_id', array('eq' => $itemId));
            $image = $option->getData();                       
         // override here as per your requirements
        $image_data = unserialize($image[0]['value']);    
        $title = explode('.',$image_data['title']);
        $fileExtension = array_pop($title);
        if($fileExtension == 'doc'||$fileExtension == 'docx'){
            $quote_path = 'custom_options/doc.png';
        }
        else if($fileExtension == 'pdf'){
           $quote_path = $quote_item->getImgData($itemId);    
           if($quote_path=='') 
            $quote_path = 'custom_options/pdf.png';          

        }else if($fileExtension == 'ppt' || $fileExtension == 'pptx'){
          $quote_path = 'custom_options/ppt.png';          

        }else if($fileExtension == 'ai'){
            $quote_path = $quote_item->getImgData($itemId);            
           if($quote_path=='') 
            $quote_path = 'custom_options/ai.png';
          
        }else if($fileExtension == 'tiff'){
            $quote_path = $quote_item->getImgData($itemId);            
           if($quote_path=='')             
          $quote_path = 'custom_options/tiff.png';
        }
        else if($fileExtension == 'psd'){
            $quote_path = $quote_item->getImgData($itemId);            
           if($quote_path=='')             
            $quote_path = 'custom_options/psd.png';          
        } else if($fileExtension == 'tiff'){
           $quote_path = $quote_item->getImgData($itemId);            
           if($quote_path=='')              
          $quote_path = 'custom_options/tiff.png';          
        }else if($fileExtension == 'eps'){
            $quote_path = $quote_item->getImgData($itemId);            
           if($quote_path=='')             
          $quote_path = 'custom_options/eps.jpg';          
        }else{
         $quote_path = $image_data['quote_path'];   
        }
        $imgpath = $objectManager->create('Mangoit\MultiplyOptions\Helper\Image')->imageResize($quote_path,'165','165');    
        $image_show =  '<span class="product-image-container" style="width:165px;"><span class="product-image-wrapper" style="padding-bottom: 100%;">
        <img class="product-image-photo" src="'.$imgpath.'" ></span></span>';        
     }
        
 
 }
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php  if(isset($image_show)){echo $image_show;} else echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()):                
                    $_optionsData = $quote_item->updateOptionPosition($_options);
                   
                ?>
                    <dl class="item-options">
                        <?php foreach ($_optionsData as $_option) :     

                        ?>
                          <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option['value']) ?>
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
          <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty">
                   <!--  <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/> -->
                        <label id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty" data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"><?php /* @escapeNotVerified */ echo $block->getQty() ?></label>
                </div>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
      
        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
