<?php //die('deiasnfd');?>

<script type="text/javascript">
require([
    'jquery',
    'Magento_Checkout/js/model/quote',
    'Magento_Checkout/js/model/shipping-rate-registry',
    'Magento_Customer/js/customer-data'

], function ($, quote, rateRegistry, customerData) {
      /*console.log( "Loaded!!" );*/

      setTimeout(
  function() 
  {
    /*console.log( "cart ready!" );*/
      var sections = ['cart'];
    customerData.invalidate(sections);
    customerData.reload(sections, true);
  }, 2000);
      setTimeout(
  function() 
  { 
    /*console.log( "summery ready!" );*/

    var address = quote.shippingAddress();
        address.trigger_reload = new Date().getTime();
        rateRegistry.set(address.getKey(), null);
        rateRegistry.set(address.getCacheKey(), null);
        quote.shippingAddress(address);
  }, 3000);
});
</script>
